python ../code/depthcharge.py dochtml newlog

python ../code/depthcharge.py --description | sed 's/^/# /' > ../DepthCharge.md
echo >> ../DepthCharge.md

echo '```' >> ../DepthCharge.md
python ../code/depthcharge.py --details >> ../DepthCharge.md
echo '```' >> ../DepthCharge.md
echo >> ../DepthCharge.md
echo 'For a better rendering and navigation of this document, please download and open [`./docs/depthcharge.docs.html`](./docs/depthcharge.docs.html), or visit <https://slimsuite.github.io/depthcharge/>.' >> ../DepthCharge.md
echo 'Documentation can also be generated by running DepthCharge with the `dochtml=T` option. (R and pandoc must be installed - see below.)' >> ../DepthCharge.md
echo >> ../DepthCharge.md
echo '## Introduction' >> ../DepthCharge.md
echo >> ../DepthCharge.md
grep -A 10000 mapped depthcharge.docs.Rmd >> ../DepthCharge.md

cp depthcharge.docs.html ../index.html
cp ../DepthCharge.md ../README.md
